-- Supabase RLS policies are provided at sql/supabase/policies.sql.
-- D1 does not have RLS: server-side authorization protects every endpoint.
-- Strict server-only data access: browser anon/authenticated cannot read or mutate these tables.
BEGIN;
ALTER TABLE public."bookmarks" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."bookmarks" FROM anon, authenticated;
GRANT ALL ON TABLE public."bookmarks" TO service_role;
ALTER TABLE public."forum_categories" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."forum_categories" FROM anon, authenticated;
GRANT ALL ON TABLE public."forum_categories" TO service_role;
ALTER TABLE public."forum_comments" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."forum_comments" FROM anon, authenticated;
GRANT ALL ON TABLE public."forum_comments" TO service_role;
ALTER TABLE public."configurations" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."configurations" FROM anon, authenticated;
GRANT ALL ON TABLE public."configurations" TO service_role;
ALTER TABLE public."debate_votes" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."debate_votes" FROM anon, authenticated;
GRANT ALL ON TABLE public."debate_votes" TO service_role;
ALTER TABLE public."feature_votes" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."feature_votes" FROM anon, authenticated;
GRANT ALL ON TABLE public."feature_votes" TO service_role;
ALTER TABLE public."comment_likes" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."comment_likes" FROM anon, authenticated;
GRANT ALL ON TABLE public."comment_likes" TO service_role;
ALTER TABLE public."moderation_logs" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."moderation_logs" FROM anon, authenticated;
GRANT ALL ON TABLE public."moderation_logs" TO service_role;
ALTER TABLE public."participation_data" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."participation_data" FROM anon, authenticated;
GRANT ALL ON TABLE public."participation_data" TO service_role;
ALTER TABLE public."poll_responses" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."poll_responses" FROM anon, authenticated;
GRANT ALL ON TABLE public."poll_responses" TO service_role;
ALTER TABLE public."polls" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."polls" FROM anon, authenticated;
GRANT ALL ON TABLE public."polls" TO service_role;
ALTER TABLE public."profiles" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."profiles" FROM anon, authenticated;
GRANT ALL ON TABLE public."profiles" TO service_role;
ALTER TABLE public."project_changes" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."project_changes" FROM anon, authenticated;
GRANT ALL ON TABLE public."project_changes" TO service_role;
ALTER TABLE public."provinces" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."provinces" FROM anon, authenticated;
GRANT ALL ON TABLE public."provinces" TO service_role;
ALTER TABLE public."rate_limits" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."rate_limits" FROM anon, authenticated;
GRANT ALL ON TABLE public."rate_limits" TO service_role;
ALTER TABLE public."reports" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."reports" FROM anon, authenticated;
GRANT ALL ON TABLE public."reports" TO service_role;
ALTER TABLE public."sessions" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."sessions" FROM anon, authenticated;
GRANT ALL ON TABLE public."sessions" TO service_role;
ALTER TABLE public."settings" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."settings" FROM anon, authenticated;
GRANT ALL ON TABLE public."settings" TO service_role;
ALTER TABLE public."simulations" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."simulations" FROM anon, authenticated;
GRANT ALL ON TABLE public."simulations" TO service_role;
ALTER TABLE public."suggestions" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."suggestions" FROM anon, authenticated;
GRANT ALL ON TABLE public."suggestions" TO service_role;
ALTER TABLE public."forum_threads" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."forum_threads" FROM anon, authenticated;
GRANT ALL ON TABLE public."forum_threads" TO service_role;
ALTER TABLE public."users" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."users" FROM anon, authenticated;
GRANT ALL ON TABLE public."users" TO service_role;
-- The application server validates session, ownership and role before every action.
COMMIT;
